/**
 * NOTE: This class is auto generated by the swagger code generator program (2.4.8).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package io.swagger.api;

import io.swagger.model.EmpleadosRsType;
import io.swagger.annotations.*;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestHeader;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RequestPart;
import org.springframework.web.multipart.MultipartFile;

import javax.validation.Valid;
import javax.validation.constraints.*;
import java.util.List;
@javax.annotation.Generated(value = "io.swagger.codegen.languages.SpringCodegen", date = "2019-09-15T18:38:52.094Z")

@Api(value = "empleados", description = "the empleados API")
public interface EmpleadosApi {

    @ApiOperation(value = "Consultar Todos los empleados", nickname = "consultarEmpleados", notes = "Retorna todos los empleados", response = EmpleadosRsType.class, tags={ "Empleados", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "EXITO", response = EmpleadosRsType.class),
        @ApiResponse(code = 400, message = "Bad request", response = EmpleadosRsType.class),
        @ApiResponse(code = 404, message = "Not found", response = EmpleadosRsType.class) })
    @RequestMapping(value = "/empleados",
        produces = { "application/json" }, 
        method = RequestMethod.GET)
    ResponseEntity<EmpleadosRsType> consultarEmpleados(@ApiParam(value = "Cabecera estándar" ,required=true) @RequestHeader(value="headerRq", required=true) String headerRq,@ApiParam(value = "servKall3" ,required=true) @RequestHeader(value="serviceID", required=true) String serviceID);

}
